### ISSUE TITLE
Sync all branches

### ISSUE THREAD

**Issue by TobKed** [TobKed/github-forks-sync-action#13]

**Comment by GWen124** [comment]
@TobKed 
Sorry, I don't understand English, what I said was translated by translation software, please forgive me if there is any problem with the sentence.
The problem I'm currently having is the following:
1. I don't know how to clone all branches of a repository, I can only clone a few branches at the same time.
2. After this update, I can't batch clone branches of different authors into the same repository.

If I encounter problems in the future, I will come back and submit again.

**Comment by TobKed** [comment]
@GWen124 no probs, I am not a native English speaker as well :)

>     1. I don't know how to clone all branches of a repository, I can only clone a few branches at the same time.

What do you mean by cloning all branches? `git clone` command clones all branches however they are remote branches.
Did you mean clone as synchronising changes from one (upstream, source) repo to another (target) repo c
so they will be exact clones?

>     2. After this update, I can't batch clone branches of different authors into the same repository.

What do you meean by `batch clone of different authors`?  Different authors suggests that there may be some conficts but I not sure what is the problem. Was it working before? Could you provide logs so I could try reproduce it?

**Comment by GWen124** [comment]
![image](https://user-images.githubusercontent.com/75674512/154978925-97714ad6-d9c9-4992-b7b0-2d17a2aeef84.png)
![image](https://user-images.githubusercontent.com/75674512/154978950-d106475d-fdf2-45df-8a4a-4ac2eea19aee.png)


The old version is okay. This is the picture I took last time, and it hasn't been uploaded.

**Comment by TobKed** [comment]
It could be caused by mistake I did in https://github.com/TobKed/github-forks-sync-action/pull/11 which I fixed and merged here: https://github.com/TobKed/github-forks-sync-action/pull/14 .
Please rerun it and let me know how it went (since you use `@master` version latest fix should be used and you don't have to change anything in your workflow)

**Comment by GWen124** [comment]
> It could be caused by mistake I did in https://github.com/TobKed/github-forks-sync-action/pull/11 which I fixed and merged here: https://github.com/TobKed/github-forks-sync-action/pull/14 .
> 
> Please rerun it and let me know how it went (since you use `@master` version latest fix should be used and you don't have to change anything in your workflow)

OK, thank you very much. I found the problem again later, and I'm coming to submit it.

Regarding the cloning of the entire warehouse branch, I don't know how to explain it. Let's take your warehouse as an example.

![image](https://user-images.githubusercontent.com/75674512/154998322-35af5794-0dc0-464d-9388-7107344f4434.png)

These are the three branches of your warehouse. How can I clone them at once?

**Comment by GWen124** [comment]
For example, the main branch of your warehouse is "master" and the other branch is "18.06". How can I clone it at one time? After all, some authors use branches to distinguish versions.

**Comment by TobKed** [comment]
@GWen124
If you wnat to update muttiple branches you can use `matrix` to parametrize it. ([docs](https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs)).
I created example workflow of syncing all branches:
```yaml
name: Sync all branches
on:
  workflow_dispatch:

jobs:

  generate-matrix:
    name: Generate matrix of branches
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix of branches
        id: set-matrix
        run: |
          upstream_repo="https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${INPUT_UPSTREAM_REPOSITORY}.git"
          upstream_dir=${INPUT_UPSTREAM_REPOSITORY##*/}
          
          git clone "${upstream_repo}"
          cd "${upstream_dir}"
          
          JSON="{\"branch\":["
          
          for branch in `git branch -a | grep remotes | grep -v HEAD`; do
              branch_trimmed=$(echo -e $branch | sed -e "s/remotes\/origin\///g")
              JSON="$JSON\"${branch_trimmed}\","
          done
          
          if [[ $JSON == *, ]]; then
            JSON="${JSON%?}"
          fi
          JSON="$JSON]}"
          
          echo $JSON | jq
        
          echo "::set-output name=matrix::$( echo "$JSON" )"

        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          INPUT_UPSTREAM_REPOSITORY: apache/airflow

  update_external_airflow_fork:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: apache/airflow
          target_repository: TobKed/airflow
          upstream_branch: ${{ matrix.branch }}
          target_branch: ${{ matrix.branch }}
          force: true
          tags: true
```
